### ISSUE TITLE
Link for 64-bit Windows dev build is broken

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPN2BankEditor#101]
![404](https://user-images.githubusercontent.com/32672779/99877677-0cb8ec80-2c00-11eb-89d0-7753f5e7a42f.PNG)

Just letting you know. It might have something to do with AppVeyor, while win32 artifact is present, 64-bit:
`Collecting artifacts...`
`No artifacts found matching 'opn2-bank-editor\opn2-bank-editor-dev-win32.zip' path`

**Comment by Wohlstand** [comment]
Damn... gonna to fix this when I get gone

**Comment by Wohlstand** [comment]
I hope this will fix the issue:
https://github.com/Wohlstand/OPN2BankEditor/commit/14b9dcd4185f9623df3d4d6d702f07049a6927fc

**Comment by Wohlstand** [comment]
Victory!
![Снимок экрана_2020-11-22_01-29-55](https://user-images.githubusercontent.com/6751442/99888999-47ec0780-2c62-11eb-86dd-d33c439007a3.png)
