### ISSUE TITLE
[Feature Request]Option to show detune values as unsigned (0-7ε)

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPN2BankEditor#102]
Some FM tone editors/utilities and textual MML formats refer to detune values as unsigned numbers:

No detune can be either `0` or `4`
`1+ε` = `1`
`1+2ε` = `2`
`1+3ε` = `3`
`1-ε` =` 5`
`1-2ε` = `6`
`1-3ε` = `7`
Also, Bamboo Tracker has such option.

**Comment by Wohlstand** [comment]
These are internal chip values, but signed values was taken from the manual. I would display both: internal and explanation what it means.

**Comment by Wohlstand** [comment]
Done! :fox_face: :+1: 
![Peek 2020-11-28 14-59](https://user-images.githubusercontent.com/6751442/100515041-65e9c880-318a-11eb-909d-6e4da802a568.gif)

**Comment by freq-mod** [comment]
Thanks! For consistency, 0 and 4 can be appended to "No change" labels, though.

**Comment by Wohlstand** [comment]
> For consistency, 0 and 4 can be appended to "No change" labels, though.

I didn't that because the translation will give two copies of the label, otherwise, I'll make the code that does `tr("No change")` and filled the `"0: %1"` and `"4: %1"`.
