### ISSUE TITLE
[Bug]Instrument list keeps jumping to GM1 Melodic bank after changing LSB

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPN2BankEditor#103]
This bug is weird, it seems to occur consistently, yet with many prerequisites. Only steps to replicate I can come up with:

1. Open this bank:  [toho.zip](https://github.com/Wohlstand/OPN2BankEditor/files/5610869/toho.zip) (WIP Pc-98 bank, might be used as example libOPNMIDI FM bank when it's finished)
2.  Change MIDI standard to "Roland GS"
3. Go to SC-88 Map Var 16
4. Change LSB to 3 and then back to 2
5. You will be thrown to default GM1 bank.

There might be other ways to replicate this behaviour, I guess.

**Comment by Wohlstand** [comment]
:thinking: 
[2020-11-28_23-50-57.mp4.zip](https://github.com/Wohlstand/OPN2BankEditor/files/5611222/2020-11-28_23-50-57.mp4.zip)

**Comment by freq-mod** [comment]
It's only bank 16 that does that, look:
[ice_video_20201128-220621_edit_0.zip](https://github.com/Wohlstand/OPN2BankEditor/files/5611245/ice_video_20201128-220621_edit_0.zip)

**Comment by Wohlstand** [comment]
Didn't reproduced at me... maybe I should try this at my Win8.1 computer?

**Comment by Wohlstand** [comment]
BLAK MAGIK!!!
[2020-11-29_00-17-23.mp4.zip](https://github.com/Wohlstand/OPN2BankEditor/files/5611254/2020-11-29_00-17-23.mp4.zip)

It reproduced on Windows build ran on Wine!

**Comment by Wohlstand** [comment]
Okay, that damn happens on Windowd, because the banks list gets be cleaned-up:
```cpp
void BankEditor::reloadBanks()
{
    ui->bank_no->clear();
    int countOfBanks = 1;
    bool isDrum = isDrumsMode();
    if(isDrum)
        countOfBanks = ((m_bank.countDrums() - 1) / 128) + 1;
    else
        countOfBanks = ((m_bank.countMelodic() - 1) / 128) + 1;
    for(int i = 0; i < countOfBanks; i++)
    {
        ui->bank_no->addItem(QString(), i);
        refreshBankName(i);
    }
}
```
because the instrument names reloading call do calling the "setMelodic()" call that calls "reloadBanks()"

:thinking:

**Comment by Wohlstand** [comment]
And I know why: QListWidget item search by wildcard sux: I found a different way to iterate items inside of it, gonna to try...

**Comment by Wohlstand** [comment]
@freq-mod , just now I made a fix, please verify the work! :fox_face:

**Comment by Wohlstand** [comment]
// I feel, I need to apply the same fix to OPL3-BE too...

**Comment by Wohlstand** [comment]
Done at OPL3-BE too.

**Comment by freq-mod** [comment]
Looks like that bug is gone, thanks!
