### ISSUE TITLE
support importing OPL musical instruments

### ISSUE THREAD

**Issue by denjhang** [Wohlstand/OPN2BankEditor#109]
I want to import an opl2 or OPL3 instrument, which can be used as an opn2 instrument after a little modification

**Comment by freq-mod** [comment]
OPL and OPN chips don't have that much in common. Registers aren't compatible, parameters have different bit depth (AR on OPL3 has 0-15 values, AR on OPN2 has 0-31 for example) and a lot of other caveats. So, I heavily doubt it's possible

**Comment by freq-mod** [comment]
Ah, I forgot. ADSR differs so wildly between these two chip families, (sustain, decay, rate scale level) instrument after import would be a total mess. The same applies to OPN -> OPL, since OPL doesn't have secondary Decay.

**Comment by denjhang** [comment]
@freq-mod In fact, there is a conversion program to realize the conversion from OPL VGM to OPN VGM. Please refer to this project https://github.com/digital-sound-antiques/vgm-conv
I tried many OPL VGM files, which can be converted to OPN normally without exception.

**Comment by Wohlstand** [comment]
Closing as abandoned.
