### ISSUE TITLE
The same crash problem as OPL3-BE

### ISSUE THREAD

**Issue by denjhang** [Wohlstand/OPN2BankEditor#115]
https://user-images.githubusercontent.com/61811583/122153504-bbbb5f00-ce95-11eb-875c-a6a7e0becb22.mp4

**Comment by denjhang** [comment]
When I deleted the code related to ASIO by myself, everything was normal. OPN2-BE has now been successfully compiled.

**Comment by Wohlstand** [comment]
Does it start now after the ASIO code got disabled? If yes, I'll close this and that issue.

**Comment by denjhang** [comment]
When the ASIO code was deleted, there was no problem at all.

**Comment by Wohlstand** [comment]
Thanks for the confirmation! :fox_face: :+1:
