### ISSUE TITLE
Tooltip text of channel debug info is not correct

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPN2BankEditor#17]
It describes the architecture of OPL3 and was a straight copy out of the other editor.
It's the text label in the top right corner.

**Comment by Wohlstand** [comment]
Yeah, you have found one of my "treasures" I must avoid in OPN2 editor, so, I'll fix this...

**Comment by jpcima** [comment]
I knew it for a bit of time, but for translation purposes the original text have better be perfect before engaging in it.

**Comment by Wohlstand** [comment]
Fixed just now!
