### ISSUE TITLE
Bad definition for frequency multiplier MUL

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPN2BankEditor#21]
The info tip of MUL refers to the OPL3 sample rate in its formula. This can't be right.
Should this be instead `53267`?

![opn2mul](https://user-images.githubusercontent.com/17614485/41657159-c1ff6c90-7492-11e8-8b7f-d7371c610049.png)

**Comment by Wohlstand** [comment]
I think, I need to check, this formula was copied from OPL3 documentation, for OPN2 it would be different, but yeah, 53267

**Comment by papiezak** [comment]
Rate scale level description also seems misleading, rather than attenuating output towards higher pitches it shortens the envelope (entirely) - attack rates become faster, decays are shortened as well.

Think of it like it's OPL3's KSR.

**Comment by Wohlstand** [comment]
Fixed on a quick hand!
