### ISSUE TITLE
Notes are played at wrong pitch after modifying parameters

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/OPN2BankEditor#32]
Steps to replicate:

- Open any bank, select any instrument
-  Play any note, for example 76)
- Change any paramenter, for example second operator's Decay 2 value (WARNING: you must do it by typing in values, using up/down UI buttons won't work)
- Hit "Play note" button once again
- That's it. Most of the time, note will be played at wrong pitch/octave. Changing previously modified parameter will give different results

This bug can be hard to replicate, since it seems to be very random.  Tested on Nuked OPN2 core.

**Comment by jpcima** [comment]
Confirmed. Also it's only a thing of the UI interaction, it's not happening with the Midi keys.
I trace a `changeNote` call which happens as number keys are typed with cursor in the edit box.
Gotta solve the mystery about what causes this.

**Comment by Wohlstand** [comment]
Looks like is need to re-send the current note number and pitch to the chip on note play request...

**Comment by jpcima** [comment]
I found that only the key-release event is passed through to the piano when typing in an edit box.
Out of this key-release the note is getting changed.
I think, by arranging the piano to store the key states pressed by keyboard, I can then discard the unmatched key-release and not act the change of note.

**Comment by papiezak** [comment]
Looks like it's fine now. Thnaks @jpcima!
