### ISSUE TITLE
Problem exporting to WOPN format

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPN2BankEditor#35]
When a GEMS banks is open and then saved as WOPN file, this WOPN file cannot be opened again.
An error is raised about a bad format.
My suspicion in on the exporter, as it is not able to open this file the wopn_file library either.

**Comment by Wohlstand** [comment]
Which GEMS bank? Any?
It's possibly some invalid data was written and reader was confused...

**Comment by Wohlstand** [comment]
Oh! Yeah, the GEMS banks are usually melodic only, and there are lacks percussions. WOPN requires to have 128:128 set as minimum. So, the WOPN needs to have one blank drums set while saving.

**Comment by jpcima** [comment]
As I was able to see, on import of the GEMS bank, the editor is displaying some garbage on the percussion side. Clearly, the editor does not appear happy to lack having an empty drum bank.

![capture du 2018-09-07 11-30-16](https://user-images.githubusercontent.com/17614485/45210996-72279980-b291-11e8-821e-95dc79a2b528.png)

**Comment by Wohlstand** [comment]
Oh, yeah, while filling the bank, you need to initialize the container to let it have blank 128:128 entries set. And, while saving the bank, it's need to guarantee the saving bank will have minimal 128:128.

Anyway, try to put break point and check, which part of WOPN parser makes "bad format"?

**Comment by jpcima** [comment]
I had it at this point in code, happening inside readInstrument.

```
        FmBank::Instrument &ins = (readPercussion) ? bank.Ins_Percussion[i] : bank.Ins_Melodic[i];
        if(!readInstrument(file, ins, version))
```

About gems, I believe it was a matter of writing this fix. I will check if new banks are working.

```
-    bank.reset(bankCount, 0);
+    bank.reset(bankCount, 1);
```

**Comment by jpcima** [comment]
The banks work! I updated a bank package into VST (btw, now having full OPN2 and ready builds :+1: )
PR will follow quickly
