### ISSUE TITLE
Global clipboard support

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/OPN2BankEditor#42]
It's would be cool to be able open two separated bank editors and copy / paste instruments between of them. For now, the clipboard is only internal and can copy and paste instruments inside of same instance of BE. It can be solved by any of ways:
* Shared memory block that will store the raw structure copy and some helpful meta-data (And, the version of BE to avoid cross-version conflicts).
* Temp file where instrument will be stored, which can be auto-imported from another instance of BE.
* Dump instrument structure as bytes array and export into OS regular clipboard.

P.S. The task is same for OPL3-BE too. Why I wrote here? I have tried to organize GENS bank into GM, but I have found it would be more convenient to open two instances of same BE and paste copied instruments into another opened bank.

**Comment by jpcima** [comment]
I vote definitely for the third way based on clipboard.
Better to avoid the complication of any IPC that implies a synchronization and resource management.

**Comment by Wohlstand** [comment]
Okay, it's now done, I have tested this on my end, and it's perfect! :fox_face: :+1: 
 @jpcima ,Thanks you, for a work!
