### ISSUE TITLE
Tomsoft instruments

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPN2BankEditor#44]
Below is an archive which contains the melodic set.
[Tomsoft.tar.gz](https://github.com/Wohlstand/OPN2BankEditor/files/2521702/Tomsoft.tar.gz)

This file has:
- a rom which has two songs, which go through all the melodics 0-127 or drums 0-127 and play them
- a gym dump of the 2 songs
- a wopn file of the melodics

I took the melodics from a GYM dump and a slightly modified importer, such that there are the 128 of them in the GM order, and allowing duplicates (as the bank has a few).
For the drums, I have not found how to make sense of the percussive dump.

**Comment by Wohlstand** [comment]
About drums: There are full PCM, he have used one damned RSC-s one... Will check the thing at home, for now I'm in the park.

**Comment by jpcima** [comment]
Yeah I tried, and also I found a problem in the process.

When I tried importing XG in Tomsoft, there was a crash. First was a problem about a badly resized intrument `store` vector, and second was another crash deeper down, that I've not researched more about.

Tomsoft into XG seemed working.

**Comment by Wohlstand** [comment]
Yeah, that I also have found yesterday, I mean crash on import out of range instruments. Yeah, for a quick, import first 128 instruments only, but then make auto-expanding of bank when out of range was found.

**Comment by Wohlstand** [comment]
After vector resizes you must to re-assing side point that refers the raw array of vector.

**Comment by Wohlstand** [comment]
[Tomsoft.wopn.zip](https://github.com/Wohlstand/OPN2BankEditor/files/2523345/Tomsoft.wopn.zip)
I did some work to normalize those instruments to correct octave (by correcting of note offsets), and I have done differently:
- I have copied "xg.wopn" into new file and opened it
- I have imported melodic set of original Tomsoft's set over mine

**Comment by Wohlstand** [comment]
Okay, I have stored this bank into `Bank_Samples/Other banks` folder, but, this issue I'll keep opened for some other discussions and will be closed later.

**Comment by Wohlstand** [comment]
Looks like this discussion is no more actual, I'll close it. The Tomsoft's instruments where left as slightly modded wopn bank with FM drums taken from xg and gems's wopn sets.
