### ISSUE TITLE
Crash on attempt to import non-GM instrument on a case of bank absence

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/OPN2BankEditor#45]
When you have count of bank less than importing instrument, the crash will happen as the reason of instruments store arrays mismatch. To fix this, it's need to check the instrument number, and then automatically expand the banks set to let instruments be correctly imported.

P.S. It's absolutely same crash on OPL3 Bank Editor as the same importer code was used in both cases.

**Comment by jpcima** [comment]
This was not sufficient. When you import by "assign" mode, you have to match the banks of destination and source.
I think it means to create a bank if it does not exists in the destination, and dstination instrument can have a different index in the store.
