### ISSUE TITLE
Importer usability

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPN2BankEditor#49]
After some work on improving the importer, I find importer use to be kind of confusing by some aspects, and it's possible to improve the user-friendlyness.

-  when an instrument is imported into the selected slot, you can't play it; you have to select another and go back to this instrument, to allow it to play.

- when under "assign" mode, the instruments assign to the melodic/percussive side of banks depending on which panel it is that is selected in the main window. In my opinion, it is not intuitive.

I prefer if the importer had a choice which says: "Where do you want the instruments to go into?".

- Same (the default choice)
- Melodics
-  Percussions

**Comment by Wohlstand** [comment]
> when an instrument is imported into the selected slot, you can't play it; you have to select another and go back to this instrument, to allow it to play.

It's an imperfection that needs to be fixed...

> when under "assign" mode, the instruments assign to the melodic/percussive side of banks depending on which panel it is that is selected in the main window. In my opinion, it is not intuitive.

Then, make the "destination" at the importer to make easier understandible the target of instrument(s) are going to be imported.

So, yeah :fox_face: :+1:

**Comment by jpcima** [comment]
The proposal #50 has implemented the changes into the importer. Is this fine?

**Comment by Wohlstand** [comment]
I didn't checked that yet as I was too tired yesterday, I'll check out this at evening and will merge.

**Comment by jpcima** [comment]
Great. A little tired here also.
I have some uncertainty on the problem of playback, considering I couldn't do a setup which reproduced it, and it haven't observed it since last importer commits.

**Comment by Wohlstand** [comment]
Closing as completed.
