### ISSUE TITLE
Support for other instrument formats

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/OPN2BankEditor#5]
Would it be possible to import instruments in TFI or DMP format? (both are rather popular and most YM2612 patches on internet are in either of these)
http://www.deflemask.com/DMP_SPECS.txt -specs of DMP instrument format
* [x] TFI
* [x] DMP

**Comment by Wohlstand** [comment]
Yes, it's possible! The specification only and sample files are needed. Thanks for spec, Ill check it out, and also, can you send me some of sample instruments for debug purposes?

**Comment by papiezak** [comment]
Thanks! Here are some .dmps then: 
[Totsugeki Mix.zip](https://github.com/Wohlstand/OPN2BankEditor/files/1499595/Totsugeki.Mix.zip)

and .tfis: 
[shiru.zip](https://github.com/Wohlstand/OPN2BankEditor/files/1499598/shiru.zip)

**Comment by Wohlstand** [comment]
Thanks, also, which spec for tfi?
When I'll come to home, I'll try to implement DMP and when you will give spec for TFI - I'll implement it too.
What about DMP: I see it may contain different data, then I must reject non-Genesis and non-FM files as "unsupported", but I hope, I'll be able to provide export into DMP too.

**Comment by papiezak** [comment]
About .tfi - http://vgmrips.net/wiki/TFI_File_Format (that's all I could find)

**Comment by Wohlstand** [comment]
Thanks!
I see it's first OPN chip, but a good thing that operator data is compatible.

**Comment by Wohlstand** [comment]
TFI has been added! https://github.com/Wohlstand/OPN2BankEditor/commit/f22b68a1a26c6025c38587fcceab2c9f5e831bb0

I even found the "TFM Music Maker" which I used to validate files: I played same files in TFM and in editor to confirm that sound is same, and I have saved some my own instruments into TFI and opened them in TFM editor and played to confirm that there are saved correctly.

DMP I'll add a bit later, that in process!

**Comment by Wohlstand** [comment]
DefleMask files are also added: https://github.com/Wohlstand/OPN2BankEditor/commit/4b8cabf8dab0554fc20866793db462568b297e4c

I have found that it has undocumented versing which I had reverse-engined to support opening of some of older versions of format. Another file types are will be rejected as "unsupported" are non-Genesis and non-FM instruments.

Because some versions are unknown, I keep this as experimental until I will recognize full versing information for this file format.

**Comment by Wohlstand** [comment]
I'll close this as no more issues received from this.
