### ISSUE TITLE
YMX banks

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPN2BankEditor#55]
Found a format of banks and its documentation : https://segaretro.org/YMX

The format is present in multiple software and there exist some instruments to be found.
In the software "Sonic QX" there are banks : `S2b-81.ymx` ` Saxman.ymx`

**Comment by Wohlstand** [comment]
Can you attach some sample files for analysis?

**Comment by jpcima** [comment]
Sure yes. Here they are.
[S2b-81.ymx.gz](https://github.com/Wohlstand/OPN2BankEditor/files/2699767/S2b-81.ymx.gz)
[Saxman.ymx.gz](https://github.com/Wohlstand/OPN2BankEditor/files/2699768/Saxman.ymx.gz)

**Comment by jpcima** [comment]
One of the software has some ability to convert as YMX instruments of some DX synths.
Posting some conversions made on the shipped files.

[Txa.ymx.gz](https://github.com/Wohlstand/OPN2BankEditor/files/2699918/Txa.ymx.gz)
[Txb.ymx.gz](https://github.com/Wohlstand/OPN2BankEditor/files/2699919/Txb.ymx.gz)
[Txc.ymx.gz](https://github.com/Wohlstand/OPN2BankEditor/files/2699920/Txc.ymx.gz)
[Txd.ymx.gz](https://github.com/Wohlstand/OPN2BankEditor/files/2699921/Txd.ymx.gz)

**Comment by jpcima** [comment]
Closed because read/write implementation was added in PR #56 .
