### ISSUE TITLE
Definitions of banks for XG and other standards

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPN2BankEditor#63]
It has these XG percussion banks.
Some numbers disagree with the naming, with value off by 1.

| Name              | MSB | LSB |
| ----------------- | ----| --- |
| 48 - Orchestra    | 000 | 048 |
| 26 - AnalogKit    | 000 | 025 |
| 25 - ElectroKit   | 000 | 024 |
|  2 - StandardKit2 | 000 | 001 |

In contrast, this is the data I collected from Sekaiju's MU1000 instruments.
On the left is `MSB:Program` with 0-indexing.

```
P127:048  "YAMAHA MU1000/MU2000 #049 SymphKit"
P127:025  "YAMAHA MU1000/MU2000 #026 AnalgKit"
P127:024  "YAMAHA MU1000/MU2000 #025 ElctrKit"
P127:001  "YAMAHA MU1000/MU2000 #002 StndKit2"
```

(in comparison, XG spec indicates MSB in 0-indexing, LSB constant at 0, and Program in 1-indexing)

**Comment by jpcima** [comment]
Actually my bad, it's just me as I try to figure out XG mappings.
It's just the *first naming* inconsistent, but rest looks fine.

A question: why do we use 000 for MSB, as documentation indicates 127?
what to map in place of the MSB 126? (SFX Kit 1/2, Techno Kit, etc..)

**Comment by Wohlstand** [comment]
Because the 127 is handled by synthesizer side and the LSB is mapped to patch change events when drums mode is on.

**Comment by jpcima** [comment]
I deduce that MSB=0 is XG 127, MSB=1 is XG 126, in context of libADLMIDI.
My current work is to put together the database of patches. (made XG set from definitions of Sekaiju, and should be able to repeat the same for MS-GS, SC88, GM2)
I will work to integrate this the editor, to facilitate the bank editing.

**Comment by jpcima** [comment]
I finished collecting the instrument set from Seikaju in one file.
Included are MU1000 XG, Microsoft GS, Roland Sound Canvas, GM Level 2. It's a large file.
https://gist.github.com/jpcima/0ace01fc2be138ea61119bf68421dafc

It converted the XG (127,120) to MSB 0, 1.
It's a flat array for static data. At runtime, I think we can construct a hash map to accelerate lookups.

**Comment by Wohlstand** [comment]
I think, we need to append one another XG list: In the set of Cakewalk Sonar 1.3 I have the list of instruments which is matching the SYXG50 and MU2000 isn't matching by some set, I have checked out... I'll append the files from Sonar where those names are defined...
[default.txt](https://github.com/Wohlstand/OPN2BankEditor/files/2831279/default.txt)

**Comment by Wohlstand** [comment]
Sonar's spec is similar, so, it's need to chop the XG part from this Sonar's dump and put as "syxg50.ins"

**Comment by jpcima** [comment]
Missing instruments are 0:0 XG percussions.

**Comment by jpcima** [comment]
No instruments missing, I did actually add these.
What misses is possibly:
- the fallback by drop of LSB on GS (as libADLMIDI does)
- the fallback by drop of MSB on XG, maybe. as hinted by sonar definitions of this form:
```
Key[16256,16]=XG Rock Kit
Key[*,16]=XG Rock Kit
```

**Comment by papiezak** [comment]
Hmmm...
When starting editor with or without loaded bank, blank entries are displayed as "+fireball" for melodic instruments and "bell tree" for percussion.
![edit shit](https://user-images.githubusercontent.com/32672779/53020830-12e0ce80-3458-11e9-98c6-76de4e409ea0.PNG)

**Comment by jpcima** [comment]
Fixed by #66, I believe. Tried the build artifact under Appveyor.

**Comment by papiezak** [comment]
That fixed this one, thanks!

**Comment by Wohlstand** [comment]
Closing as completed/abandoned.
