### ISSUE TITLE
SSG-EG problem (Need to replace GENS with MAME and Nuked OPN2 emulators)

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/OPN2BankEditor#7]
I made some recordings  comparing MAME's and Gens' output when I "noticed" THIS
https://instaud.io/1Z0Z - recorded using Deflemask, MAME emulation
https://instaud.io/1Z10 - recorded using bank editor, Gens 2.10 core

Difference is rather apparent...
[bird.zip](https://github.com/Wohlstand/OPN2BankEditor/files/1866186/bird.zip)
This is instrument in question.

**Comment by Wohlstand** [comment]
Gens's core is very outdated and inaccurate. I gonna replace it with MAME's. Nuked OPN2 emulator is a very accurate thing, BUT, it eats 10x much harder than even Nuked OPL3, therefore I can't use more than 3 chips on a same CPU core without of chopping.

**Comment by papiezak** [comment]
I have suspected that. But tbh, bank editor doesn't need more than just one emulated chip, so Nuked OPN2 implementation wouldn't be so problematic (correct me if I'm wrong)

Also, would it be possible to have instances of Nuked emulator running on more than one core? 
_Its rather annoying to have 3.1 GhZ i5-2400 cpu and still have somewhat  choppy sound_

P.S: http://www.deflemask.com/forum/bug-reports/high-cpuram-usage-on-64-bit-linux/msg5644/#msg5644 (deflemask which employs MAME core can run perfectly 1.1 GhZ celeron CPU so performance wise it's not bad option.

**Comment by Wohlstand** [comment]
One Nuked OPN2 core still require powerful core, so, as begin, I'll implement a switchable emulation cores for now, then I'll adapt MAME to use it in libOPNMIDI and here too.

**Comment by Wohlstand** [comment]
Just now I have added MAME ym2612 taken from VGMPlay project. That is experimental, and if newer/better version of that emulator will be found, I'll apply it.

**Comment by papiezak** [comment]
> if newer/better version of that emulator will be found, I'll apply it.

I have found something:
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/sound/ym2612.c

**Comment by Wohlstand** [comment]
I have analyzed that, and I found some things in the code, and also noted in changelog:

> - removed unused multichip support
Without multi-chip will be impossible to use in libOPNMIDI as multi-chip is required and widely used to excite 6 channels limit.

>  - removed input clock / output samplerate frequency ratio, chip now always run at (original) internal sample frequency

This requires some tweaking around to be able use that. And I see it's a very different way than with Nuked OPN2 emulator.

So, that emulator requires some polishing to use it in libOPNMIDI and even here.

**Comment by papiezak** [comment]
OK I see. But:

> - improved 9-bit DAC emulation accuracy

> - added discrete YM2612 DAC distortion emulation ("ladder effect")

It would be great if there was a way to "backport" these features into emulator that's now in use.

**Comment by Wohlstand** [comment]
I have analyzed emulator I have - it's latest MAME (compared to current master source in official MAME repo)

**Comment by papiezak** [comment]
Uhh I just spotted yet another weird behaviour:

It seems that notes below 20 (G#0) are off by one octave (?)

https://instaud.io/207T - G#0 and G-0 as in deflemask
https://instaud.io/207U -G#0 and G-0 as in bank editor
Every core (including MAME and Nuked) is affected.

**Comment by Wohlstand** [comment]
Just now I checked that, and latest build gives same sounding as your DefleMask demo. MAME-based core gives more sharpness as it uses 44100 sample rate on generation process which results different sounding than real chip which uses persistent sample rate. I think, you need to re-take bank editor again to have it more fresh as I also applied the fix of [this crap](https://github.com/nukeykt/Nuked-OPN2/issues/6) by changing of frequency generation to avoid damaged playback of G# notes with pitch modulator thing enabled.

**Comment by papiezak** [comment]
Just I realized the following:
I imported that instrument and a melodic and it sounds fine but if to import it as a percussive one, it's broken.

**Comment by Wohlstand** [comment]
As percusive: I guess, it's some damned logic imported from old ALDMIDI and it is totally invalid and completely dropped away everywhere, except of OPN2 Bank Editor as I see... Damn! Gotta to fix that...

**Comment by Wohlstand** [comment]
Okay, Just now I removed that old crap and everything must be fine, please test when it will be built by AppVeyour :wink:

**Comment by papiezak** [comment]
Fixed; thanks!

**Comment by Wohlstand** [comment]
I'll keep this opened until you will confirm that no more issues with sounding on some cases or after week/month

**Comment by Wohlstand** [comment]
Okay, as you wasn't reported anything and you even made a complete GS bank, I'll close this.

**Comment by Wohlstand** [comment]
Did you played "Bank Editor Mame" same note? Seems you played it with a different note. Anyway, the difference is because of variable clock and sample rate which is not matching the real chip. Nuked does fixed internal sample rate and the resampling is doing when generating output.

**Comment by papiezak** [comment]
> Did you played "Bank Editor Mame" same note? Seems you played it with a different note

100% percent sure it was the same note - 86 (D-6).

> Seems DefleMask uses OR modified emulator or tweaks over it with using of fixes sample rate and post-resamling the output.

Highly doubt it; it wasn't updated since 2016, after all. About sample rate, it's most likely 44100 Hz.

**Comment by Wohlstand** [comment]
> 100% percent sure it was the same note - 86 (D-6).

Yeah, I see, anyway, try my ride cymbals on Nuked and on MIME and there are also will sound differently.

> Highly doubt it; it wasn't updated since 2016, after all. About sample rate, it's most likely 44100 Hz.

Editor also outputs 44100 Hz. I meant the sample ride inside of emulator which generates the output which resampling into 44100 hz outside of emulator and sending into output stream which is 44100 hz. For now at me MIME emulator does output of 44100 Hz and because of internal sample rate different from chip real sample rate, the noise generator will produce different output.

**Comment by Wohlstand** [comment]
So, I will need to set fixed sample rate to MIME and do the resampling of output into sample rate of output stream. Then will be a guarantee the output will match Nuked or real chip.
