### ISSUE TITLE
Bug when importing instrument with no item selected on a main window list

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/OPN2BankEditor#84]
Rather minor bug, but anyway:
1. Open bank editor with no bank loaded, don't click on any item on an instrument list yet
2. Import an external instrument (either single one, or from a bank)
3. When attempting to import it, an error will pop up, so select any target instrument from main window and proceed...
4. Instrument will get imported properly, but there won't be any sound until you change any FM parameter or move to different blank entry on instrument list and forth.

Happens on OPL bank editor as well.

**Comment by jpcima** [comment]
I think, the importer just needs to resend patch if the active selection was overwritten.
Or, to just not care at all and sendPatch() every time.

After a quick try, a line `m_main->sendPatch();` at the bottom of importer.cpp/`on_doImport_clicked` fixes the problem.
