### ISSUE TITLE
VGM importer glitchy behaviour

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPN2BankEditor#94]
On some rare occasions, VGM importer won't detect every instrument in .vgm file.
 example - [15 - Expander.zip](https://github.com/Wohlstand/OPN2BankEditor/files/4345060/15.-.Expander.zip) - importer sees only 3 instruments, while there are much more than that (such as detuned piano playing on YM2612 Channel 0 and 1, is missing).

**Comment by Wohlstand** [comment]
I guess, because they are PSG instruments which aren't supported yet :thinking:

**Comment by Wohlstand** [comment]
I trying to listen a song, and I hear some similar to PSG, lemme dump this VGM file into text file :thinking:

**Comment by Wohlstand** [comment]
Yes, I did the full dump, and I see lot of `SN76496` related commands, which were not handling as instruments.

**Comment by freq-mod** [comment]
there are psg instruments, sure but there are a few FM sounds that aren't handled

**Comment by Wohlstand** [comment]
Damn, I tried to import instruments from this file:
[Earthworm Jim 2 - Anything But Tangerines.vgz.zip](https://github.com/Wohlstand/OPN2BankEditor/files/5011981/Earthworm.Jim.2.-.Anything.But.Tangerines.vgz.zip)
And I got two of them only...

**Comment by freq-mod** [comment]
There is a VGM player called MDPlayer which allows you to see FM parameters as file is being played, so that one can be helpful while debugging

**Comment by freq-mod** [comment]
I tried to research this bug, seems like that kind of VGMs that aren't read at all (there are such cases, see zip) or read incompletely are of version 1.50. Anything other than that doesn't display such behaviour, but can be other way round - ridden with duplicates or near-duplicates
Example - [vgm.zip](https://github.com/Wohlstand/OPN2BankEditor/files/5397662/vgm.zip) - YM2608 VGM ver. 1.71, produced by BambooTracker, bank editor sees almost 300 instruments

**Comment by Wohlstand** [comment]
Good news, just now I took care of this, and I fixed the real reason for this bug: because of improper handling of 0x8n commands, there was caused a wrong offset that led to the breakage of the further command parsing. Should work fine now, @freq-mod, can you test this?

**Comment by freq-mod** [comment]
[Sonic 3 & Knuckles - Icecap Zone 1.vgm.zip](https://github.com/Wohlstand/OPN2BankEditor/files/7529700/Sonic.3.Knuckles.-.Icecap.Zone.1.vgm.zip) -anotherproblem is created I'm afraid,this file contains allegedly 130 instruments (I don't think so), some of them are exact duplicates

**Comment by Wohlstand** [comment]
The reason for duplicates is because I guess, there are some cases where some characteristics got toggled at the instrument like the LFO level or something also. Maybe add some options to configure VGM importer for duplicates detection behavior and make it ignore LFO changes and something also?

**Comment by freq-mod** [comment]
Good idea

**Comment by Wohlstand** [comment]
Also, there is some music where CC74 implemented and it alters the modulators, so, it will obviously produce the ton on different instruments. Adding an extra heuristic would make other issues, that should be done as togglable properties, and could be made as a different discussion, the main problem in a form of missing instruments has been resolved.
